# Generated by Django 4.2.2 on 2023-06-13 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppStein', '0002_clientes_crearcuenta_empleados_inicio_nosotros_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearCuenta',
            new_name='Registrarse',
        ),
    ]
